version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kong-migrations:
    image: kong/kong-gateway:3.3
    container_name: kong_migrations
    command: kong migrations bootstrap
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    depends_on:
      - postgres

  kong:
    image: kong/kong-gateway:3.3
    container_name: kong_gateway
    restart: always
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    depends_on:
      - kong-migrations

  backend:
    build: ./backend
    container_name: backend_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://kong:kong@postgres:5432/kong
    env_file:
      - ./backend/.env  # Load environment variables from .env file
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend_api
    restart: always
    ports:
      - "8080:80"

volumes:
  postgres_data:
